import "./globals.css";
import localFont from "next/font/local";

const myFont = localFont({ src: "../public/vazir.ttf" });
export const metadata = {
  title: "Blog NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="en" dir="rtl">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
